export const metronicComponents = [
  {
    component: "Primary Button",
    type: "Button",
    text: "Save, Submit",
    bgColorTailwind: "bg-blue-500",
    frontColorTailwind: "text-white",
    description: "Main actions. Rounded corners (4px), hover: #187DE4.",
    code: `<button className="bg-blue-500 text-white px-4 py-2 rounded hover:bg-[#187DE4]">Save</button>`,
  },
  {
    component: "Danger Button",
    type: "Button",
    text: "Delete, Cancel",
    bgColorTailwind: "bg-red-500",
    frontColorTailwind: "text-white",
    description: "Destructive actions. Hover: #EE2D41.",
    code: `<button className="bg-red-500 text-white px-4 py-2 rounded hover:bg-[#EE2D41]">Delete</button>`,
  },
  {
    component: "Outline Button",
    type: "Button",
    text: "Export, Settings, Import",
    bgColorTailwind: "bg-transparent",
    frontColorTailwind: "text-blue-500",
    description:
      "Border: 1px solid #3699FF. Hover bg: rgba(54, 153, 255, 0.1).",
    code: `<button className="bg-transparent text-blue-500 px-4 py-2 rounded border border-blue-500 hover:bg-[rgba(54,153,255,0.1)]">Export</button>`,
  },
  {
    component: "Secondary Button",
    type: "Button",
    text: "Back, Close",
    bgColorTailwind: "bg-gray-200",
    frontColorTailwind: "text-gray-700",
    description: "Secondary actions. Border: 1px solid #E4E6EF.",
    code: `<button className="bg-gray-200 text-gray-700 px-4 py-2 rounded border border-[#E4E6EF]">Back</button>`,
  },
  {
    component: "Navbar (Top)",
    type: "Navigation",
    text: "Home, Account",
    bgColorTailwind: "bg-gray-900",
    frontColorTailwind: "text-white",
    description: "Fixed top. Icon size: 18px. Hover: #2B2B40. Active: #3699FF.",
    code: `<nav className="bg-gray-900 text-white fixed top-0 w-full p-4">Home</nav>`,
  },
  {
    component: "Front Arrow",
    type: "Icon",
    text: "—",
    bgColorTailwind: "bg-transparent",
    frontColorTailwind: "text-gray-500",
    description:
      "Icon: /icons/duotune/arrows/arr061.svg. Used in carousels or sliders.",
    code: `<img src="/icons/duotune/arrows/arr061.svg" className="text-gray-500" alt="Next" />`,
  },
  {
    component: "Back Arrow",
    type: "Icon",
    text: "—",
    bgColorTailwind: "bg-transparent",
    frontColorTailwind: "text-gray-500",
    description: "Icon: /icons/duotune/arrows/arr062.svg.",
    code: `<img src="/icons/duotune/arrows/arr062.svg" className="text-gray-500" alt="Previous" />`,
  },
  {
    component: "Pagination Active",
    type: "Pagination",
    text: "1",
    bgColorTailwind: "bg-blue-500",
    frontColorTailwind: "text-white",
    description: "Current page indicator. Inactive: #E4E6EF. Hover: #187DE4.",
    code: `<button className="bg-blue-500 text-white px-3 py-1 rounded hover:bg-[#187DE4]">1</button>`,
  },
  {
    component: "Pagination Item",
    type: "Pagination",
    text: "2, 3, Next",
    bgColorTailwind: "bg-gray-100",
    frontColorTailwind: "text-gray-700",
    description: "Clickable page numbers. Border-radius: 4px. Hover darkens.",
    code: `<button className="bg-gray-100 text-gray-700 px-3 py-1 rounded hover:bg-gray-200">2</button>`,
  },
  {
    component: "Search Input",
    type: "Input",
    text: "Search...",
    bgColorTailwind: "bg-white",
    frontColorTailwind: "text-gray-700",
    description:
      "Search field. Border: 1px solid #E4E6EF. Icon: /icons/duotune/general/gen021.svg.",
    code: `<input className="bg-white text-gray-700 border border-[#E4E6EF] px-3 py-2 rounded" placeholder="Search..." />`,
  },
  {
    component: "Modal Popup",
    type: "Modal",
    text: "Edit User, Confirm",
    bgColorTailwind: "bg-white",
    frontColorTailwind: "text-gray-800",
    description:
      "Modal container. Header bold, 600. Shadowed with center screen alignment.",
    code: `<div className="bg-white text-gray-800 p-6 rounded shadow-md max-w-md mx-auto">Edit User</div>`,
  },
  {
    component: "Input Field",
    type: "Input",
    text: "Placeholder text",
    bgColorTailwind: "bg-white",
    frontColorTailwind: "text-gray-700",
    description: "Border: 1px solid #E4E6EF, focus: #3699FF.",
    code: `<input className="bg-white text-gray-700 border border-[#E4E6EF] focus:outline-none focus:ring focus:border-blue-500 px-3 py-2 rounded" placeholder="Text" />`,
  },
  {
    component: "Disabled Input",
    type: "Input",
    text: "Disabled",
    bgColorTailwind: "bg-gray-50",
    frontColorTailwind: "text-gray-400",
    description: "Cursor: not-allowed. Border: 1px solid #EBEDF3.",
    code: `<input className="bg-gray-50 text-gray-400 border border-[#EBEDF3] px-3 py-2 rounded cursor-not-allowed" disabled value="Disabled" />`,
  },
  {
    component: "Dropdown Menu",
    type: "Select",
    text: "Select Option",
    bgColorTailwind: "bg-white",
    frontColorTailwind: "text-gray-700",
    description: "Arrow icon: #7E8299. Dropdown bg: #FFFFFF.",
    code: `<select className="bg-white text-gray-700 border border-[#E4E6EF] px-3 py-2 rounded"><option>Select Option</option></select>`,
  },
  {
    component: "Checkbox",
    type: "Form",
    text: "Agree to terms",
    bgColorTailwind: "bg-white",
    frontColorTailwind: "text-blue-500",
    description: "Checkmark color: #3699FF. Border: 1px solid #E4E6EF.",
    code: `<label className="flex items-center"><input type="checkbox" className="accent-blue-500 mr-2" /> Agree to terms</label>`,
  },
  {
    component: "Radio Button",
    type: "Form",
    text: "Option 1",
    bgColorTailwind: "bg-white",
    frontColorTailwind: "text-blue-500",
    description: "Selected dot color: #3699FF.",
    code: `<label className="flex items-center"><input type="radio" className="accent-blue-500 mr-2" name="option" /> Option 1</label>`,
  },
  {
    component: "Card Header",
    type: "Card",
    text: "User Profile",
    bgColorTailwind: "bg-gray-50",
    frontColorTailwind: "text-gray-800",
    description:
      "Bold (600), padding: 1.5rem. Border-bottom: 1px solid #EBEDF3.",
    code: `<div className="bg-gray-50 text-gray-800 font-semibold p-6 border-b border-[#EBEDF3]">User Profile</div>`,
  },
  {
    component: "Table Row (Hover)",
    type: "Table",
    text: "—",
    bgColorTailwind: "bg-gray-50",
    frontColorTailwind: "text-gray-700",
    description: "Highlight on hover. Alternate rows: #FFFFFF.",
    code: `<tr className="bg-gray-50 hover:bg-gray-100 text-gray-700"><td>Row Data</td></tr>`,
  },
  {
    component: "Success Alert",
    type: "Alert",
    text: "Success!",
    bgColorTailwind: "bg-teal-100",
    frontColorTailwind: "text-teal-500",
    description: "Icon: #1BC5BD. Auto-dismiss in 5s.",
    code: `<div className="bg-teal-100 text-teal-500 p-4 rounded">Success!</div>`,
  },
  {
    component: "Error Toast",
    type: "Toast",
    text: "Failed to save!",
    bgColorTailwind: "bg-red-100",
    frontColorTailwind: "text-red-500",
    description: "Fixed position top-right. Close icon: #F64E60.",
    code: `<div className="bg-red-100 text-red-500 p-4 rounded fixed top-4 right-4">Failed to save!</div>`,
  },
  {
    component: "Sidebar (Active)",
    type: "Navigation",
    text: "Dashboard",
    bgColorTailwind: "bg-blue-500",
    frontColorTailwind: "text-white",
    description: "Active item indicator. Icon size: 20px.",
    code: `<div className="bg-blue-500 text-white p-4 flex items-center"><span className="text-lg">📊</span> Dashboard</div>`,
  },
  {
    component: "Badge (Pending)",
    type: "Badge",
    text: "Pending",
    bgColorTailwind: "bg-yellow-100",
    frontColorTailwind: "text-yellow-500",
    description: "Pill-shaped, font-size: 0.75rem.",
    code: `<span className="bg-yellow-100 text-yellow-500 px-3 py-1 rounded-full text-xs">Pending</span>`,
  },
  {
    component: "Tooltip",
    type: "Tooltip",
    text: "Click to edit",
    bgColorTailwind: "bg-gray-800",
    frontColorTailwind: "text-white",
    description: "Arrow color: #181C32. Font-size: 0.8rem.",
    code: `<div className="relative group"><span className="underline">Edit</span><div className="absolute hidden group-hover:block bg-gray-800 text-white text-xs p-2 rounded top-full mt-1">Click to edit</div></div>`,
  },
  {
    component: "Progress Bar",
    type: "Progress",
    text: "75%",
    bgColorTailwind: "bg-gray-200",
    frontColorTailwind: "text-blue-500",
    description: "Height: 6px. Animated on load.",
    code: `<div className="bg-gray-200 h-1.5 w-full"><div className="bg-blue-500 h-1.5 w-3/4 animate-pulse"></div></div>`,
  },
  {
    component: "Tabs (Active)",
    type: "Tabs",
    text: "Profile",
    bgColorTailwind: "bg-white",
    frontColorTailwind: "text-blue-500",
    description: "Border-bottom: 2px solid #3699FF.",
    code: `<button className="bg-white text-blue-500 border-b-2 border-blue-500 px-4 py-2">Profile</button>`,
  },
  {
    component: "Avatar",
    type: "Image",
    text: "—",
    bgColorTailwind: "bg-gray-100",
    frontColorTailwind: "",
    description: "Border: 3px solid #FFFFFF. Size: 40px.",
    code: `<img src="/avatar.png" alt="Avatar" className="w-10 h-10 rounded-full border-4 border-white" />`,
  },
  {
    component: "Divider",
    type: "Layout",
    text: "—",
    bgColorTailwind: "bg-gray-300",
    frontColorTailwind: "",
    description: "Thickness: 1px. Margin: 16px 0.",
    code: `<hr className="bg-gray-300 h-px my-4" />`,
  },
  {
    component: "Loader (Spinner)",
    type: "Feedback",
    text: "—",
    bgColorTailwind: "bg-blue-500",
    frontColorTailwind: "",
    description: "Size: 24px. Animation: spin 1s linear infinite.",
    code: `<div className="w-6 h-6 border-4 border-blue-500 border-t-transparent rounded-full animate-spin"></div>`,
  },
];
